### ISSUE TITLE
Inner Exception: Entity Framework - No such table

### ISSUE THREAD

**Issue by HumairaSid** [HumairaSid/EFCoreBasicCaching#1]
SqliteException: SQLite Error 1: 'no such table: Menu'.
Exception Detail
Microsoft.EntityFrameworkCore.DbUpdateException
  HResult=0x80131500
  Message=An error occurred while saving the entity changes. See the inner exception for details.
  Source=Microsoft.EntityFrameworkCore.Relational
  StackTrace:
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IList`1 entriesToSave)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(StateManager stateManager, Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at EFCoreBasicCaching.Program.Main(String[] args) in C:\Users\User\source\repos\EFCoreBasicCaching\EFCoreBasicCaching\Program.cs:line 16

  This exception was originally thrown at this call stack:
    [External Code]

Inner Exception 1:
SqliteException: SQLite Error 1: 'no such table: Menu'.

**Comment by rigazilla** [comment]
see https://github.com/rigazilla/Infinispan.Hotrod.EFCaching/issues/12

**Comment by HumairaSid** [comment]
Closed: 

Need to add"dbContext.Database.EnsureCreated();"
